import { NextRequest, NextResponse } from 'next/server'
import { createServerClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'

const SIGNED_URL_EXPIRY_SECONDS = 3600 // 1 hour

export async function GET(req: NextRequest) {
  // ── Auth guard ─────────────────────────────────────────────────────────────
  const supabase = createServerClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { data: profile } = await supabase
    .from('users')
    .select('is_admin')
    .eq('id', user.id)
    .single()

  if (!profile?.is_admin) return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

  // ── Path validation ────────────────────────────────────────────────────────
  const path = req.nextUrl.searchParams.get('path') ?? ''

  // Only allow paths that were generated by buildStoragePath (starts with uploads/).
  // This prevents path traversal (e.g. ../../../etc/passwd).
  if (!path.startsWith('uploads/') || path.includes('..')) {
    return NextResponse.json({ error: 'Invalid path.' }, { status: 400 })
  }

  // ── Generate signed URL ────────────────────────────────────────────────────
  const admin = createAdminClient()
  const { data, error } = await admin.storage
    .from('cvs')
    .createSignedUrl(path, SIGNED_URL_EXPIRY_SECONDS)

  if (error || !data) {
    console.error('[api/admin/cvs]', error)
    return NextResponse.json({ error: 'Could not generate download link.' }, { status: 500 })
  }

  return NextResponse.json({ url: data.signedUrl })
}
